POST http://127.0.0.1:8000/users/users
Content-Type: application/json

{
  "username": "1",
  "email": "1@example.com",
  "password": "1",
  "role": "user"
}

###

POST http://127.0.0.1:8000/review/5
Content-Type: application/json

{
  "reviewname": "Sandels",
  "reviewDescription": "very good",
  "reviewRating": 3.25,
  "imageUrl": "user.jpg",
  "category": "beer"
}

###

GET http://127.0.0.1:8000/users/users

###

DELETE http://127.0.0.1:8000/users/1

###
GET http://127.0.0.1:8000/users/3


### login
POST http://127.0.0.1:8000/auth/token
Content-Type: application/json

{
  "email": "1@example.com",
  "password": "1"
}

###
GET http://127.0.0.1:8000/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzM4NDA0MzI3fQ.WI-jcMPauu1SyxUrRgo9j1f9CNVhMycMNAK3nP1ZvFY
